# =============================================================================
# INSTRUMENTED APP - KUBERNETES MANIFEST
# Deploy: kubectl apply -f examples/instrumented-app/manifests/deployment.yaml
# =============================================================================

# -----------------------------------------------------------------------------
# NAMESPACE
# -----------------------------------------------------------------------------
apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    name: apps

---
# -----------------------------------------------------------------------------
# INSTRUMENTED-APP (formerly test-app)
# -----------------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: instrumented-app
  namespace: apps
  labels:
    app: instrumented-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: instrumented-app
  template:
    metadata:
      labels:
        app: instrumented-app
    spec:
      containers:
        - name: instrumented-app
          image: instrumented-app:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 3333
          env:
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: "http://otel-collector.observability.svc.cluster.local:4318/v1/traces"
            - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
              value: "http://otel-collector.observability.svc.cluster.local:4318/v1/metrics"
            - name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
              value: "http://otel-collector.observability.svc.cluster.local:4318/v1/logs"
            - name: OTEL_LOG_LEVEL
              value: DEBUG
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 3333
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3333
            initialDelaySeconds: 5
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: instrumented-app
  namespace: apps
  labels:
    app: instrumented-app
spec:
  selector:
    app: instrumented-app
  ports:
    - name: http
      port: 3333
      targetPort: 3333
